Update for flake8 v3.6
qiime2/library-old pull request #21
Opened 2018-10-31 23:20 UTC by ChrisKeefe

minor changes for flake8 compliance

2018-11-20 14:07 UTC, thermokarst requested changes
> E ImportError: No module named 'django'

This is probably because your [development environment](https://github.com/qiime2/library#development-quickstart) is missing the `django` dependency!

Just pulled down locally and had one error:

```bash
flake8
./library/plugins/tests/test_views.py:1:1: F401 'unittest' imported but unused
```

Otherwise, this PR is good to go!

2018-11-20 22:55 UTC, ChrisKeefe commented
Tried to align my commit history with master using rebase, and it led me to force-push my updates here. Sorry if that breaks your process at all, @thermokarst .

Not seeing Travis on my end. Different for you?

2018-11-21 15:38 UTC, thermokarst approved these changes

2018-11-21 15:38 UTC, thermokarst commented
I give up. Merging as-is, we can address any issues in a follow-up PR.

2018-11-21 15:38 UTC, merged

2018-11-21 15:40 UTC, thermokarst commented
lol, I see the problem now --- it should be `.travis.yml`, not `travis.yml`!