Initial commit for bug #19 fix.
qiime2/library-old pull request #22
Opened 2018-11-15 15:55 UTC by raptorace27

### Brief summary:
We fixed the issue that prevented authors from editing their plugins by:

 + Creating a new field in the Plugin model, 'created_by'
    + This field would be automatically populated with the current user when they attempt to save a new instance of a plugin. This provides a fail safe to the original author in the event that they forget to add themselves as authors, and subsequently not having permission to edit.

NOTE: This fix only works from plugins that are created from **now on**, any previous plugins will need to be updated with correct authors.

**Co-authored-by:** 
- - Joseph Remy - [J1411](https://github.com/J1411)
- - Tanner Massahos - [tanman987](https://github.com/tanman987)
- - Julian Bell - [jbell-97](https://github.com/jbell-97)

---

Include any questions for reviewers, screenshots, sample outputs, etc.

2018-11-15 17:28 UTC, thermokarst requested changes
Can you drop the `.idea` files from this PR? Also, a pretty high-level comment --- this looks great 🎉 , but, the issue referenced requests that the _current user_ must be listed as an author. I mention this because we don't need a new "created_by" field --- that is what the author list is (everyone who is an author is a creator, make sense? This new field doesn't allow for multiple "creators", either, which is a problem). My suggestion for fixing this is to modify the form's validation step to check if the current request's user is in the list of authors, that way if they aren't you can just use the `Form` API in Django to raise a nice error message for users. Sorry the original issue wasn't clearer --- if you have any questions please let me know, and thanks again!

2018-11-15 17:28 UTC, thermokarst commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
Can you please remove all of the files in this `.idea` dir? That looks like some noise from your editor (I suggest updating your global git config to prevent these files from being committed to _any_ repo).

2018-11-15 17:39 UTC, raptorace27 commented
Oh dang I should have read the issue more carefully, my bad! I can make those modifications so that if the current user is not added to the author list it raises an error. Also, sorry about the .idea files I'll make sure those are left out of the next commit. Thanks for your patience and suggestions we greatly appreciate it!

2018-11-19 00:15 UTC, raptorace27 commented
Hey sorry I had to revert that last commit because some debauchery...

2018-11-19 00:26 UTC, raptorace27 commented
Okay! Let me know if this is what you're looking for. I added some custom validation to the author formsets  in plugins/forms.py which will raise a ValidationError in the event the current user is not added to the author list. 

I was also wondering if you guys had a plan to make the author list dynamic in the sense that as authors are added, there is some form of auto updating the list to give the user the ability to add more authors. If not we can try to get together something that solves this issue!

2018-11-20 13:41 UTC, thermokarst requested changes
Thanks @raptorace27! This looks awesome and works as expected! I pulled it down locally and kicked the tires and I think it does the trick. My inline review comments have to do with a few minor linting, style adjustments, and miniscule code tweaks. Once those are addressed this PR is ready to merge! Let me know if you have any questions! 🥇

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +            raise forms.ValidationError('You must enter yourself as an author', code='author_error1')
Awesome! Can you update the error message to say the following:

`You must include yourself as an author. Save the plugin to add additional authors.`

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +from django.forms import BaseInlineFormSet
Imported but unused.

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +        Plugin, PluginAuthorship,
Trailing whitespace

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +
Trailing whitespace

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +    # Overriding the clean() to add our custom validation.
Probably not necessary, since this comment just describes the exact same thing as the line below. A general rule of thumb I like to keep in mind is: code explains _how_, comments explain _why_.

Also, for `flake8`, you need a blank line between the end of the constructor and the start of this `clean` method.

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +        if any(self.errors):
I don't think this check is necessary, the validation is appropriate with other errors, for example:

![screen shot 2018-11-20 at 6 21 54 am](https://user-images.githubusercontent.com/274668/48776273-adc8e180-ec8c-11e8-9530-f38e1c62bc30.png)

![image](https://user-images.githubusercontent.com/274668/48776292-bb7e6700-ec8c-11e8-83ad-2d3cb93a0935.png)

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +        user_in_author_list = False
Maybe it makes sense to "invert" this flag, that way below your check can be `if user_not_in_author_list:`, which I think is a bit easier to parse. What do you think?

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +        # Runs through every form (author) to see if the current user is entered.
Same comment as above --- does this comment bring additional value or provide context for the code below? I would suggest no --- I think the code is clean and speaks for itself without this comment.

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +            # If the User is in the author list, then set user_in_author_list flag to true.
Same comment as above --- does this comment bring additional value or provide context for the code below? I would suggest no --- I think the code is clean and speaks for itself without this comment. In this case this comment is essentially psuedocode.

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +        # User is not in author list, raise appropriate error.
Same comment as above --- does this comment bring additional value or provide context for the code below? I would suggest no --- I think the code is clean and speaks for itself without this comment.

I'm not trying to be a comment killer here, rather, I am advocating for the code to speak for itself:

![image](https://user-images.githubusercontent.com/274668/48776815-0fd61680-ec8e-11e8-8a1f-8bfc894874e4.png)

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +
extra line

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/forms.py
> +
extra line

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/views.py
> +                                    user=self.request.user)
I don't think this kwarg is necessary, since you aren't consuming it in `get_context_data` above, rather, you are getting the user off of the request object (which I think is the right way to do that).

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/views.py
> +                    user=self.request.user,
I don't think this kwarg is necessary, since you aren't consuming it in get_context_data above, rather, you are getting the user off of the request object (which I think is the right way to do that).

2018-11-20 13:41 UTC, thermokarst commented on library/plugins/views.py
> +        ctx = self.get_context_data\
Can you change the formatting of this back to how it was before? This won't pass `flake8` linting.

2018-11-20 13:41 UTC, thermokarst commented on library/templates/plugins/plugin_form.html
> +            <tr class="has-text-danger"><td colspan="3">
A general comment on this file: I think the only functional code changes are here on [L63](https://github.com/qiime2/library/pull/22/files#diff-6f110a3fac8a0f89caa4ad56701e8b0fR63)-[L66](https://github.com/qiime2/library/pull/22/files#diff-6f110a3fac8a0f89caa4ad56701e8b0fR66) - the rest of the diff here is just formatting noise. In general we ask that these changes be removed, since they pollute the git history. In particular, if you run `git blame` to look at [L86 for example](https://github.com/qiime2/library/pull/22/files#diff-6f110a3fac8a0f89caa4ad56701e8b0fR86), you will see that the latest change was in this PR. This could potentially be confusing because then you are left figuring out "why on earth did this line change when it has nothing to do with the stated mission of that PR?" Does that make sense?

2018-11-20 13:41 UTC, thermokarst commented on library/templates/plugins/plugin_form.html
> +
If you run `flake8` in the root of the repo you should get a nice report of style-related changes to make, including this blank line.

2018-11-20 13:46 UTC, thermokarst commented
As a separate follow-up to this question:

> I was also wondering if you guys had a plan to make the author list dynamic in the sense that as authors are added, there is some form of auto updating the list to give the user the ability to add more authors. 

Great question! That is certainly on our radar, but no concrete plans for that. If you are interested in writing up an issue that would be awesome (and even more awesome if a code change came with it)! No pressure though ;-)

2018-11-21 01:22 UTC, raptorace27 commented
@thermokarst this was an excellent review, there obviously is a lot I need to change but I appreciate the level of detail you provided! I'll change everything as expected with regards to the comments above and get the final commit back to you guys by the end of this week. I will also research and test ways of making the formset dynamic so we can add multiple authors in one sha-bang. 

Thanks again for the review, and also we LOVED the memes they had us laughing hard haha :)

2018-11-28 17:58 UTC, raptorace27 commented
Alrighty @thermokarst super sorry for the late commit, so far we're happy with this but if we need to change anything please let us know. Again, we really appreciate your feedback <3

2018-12-06 15:42 UTC, thermokarst requested changes
LGTM! One minor typo in the error message (looks like this was introduced in your latest force-push). Once that is resolved this will be merged! Thanks!

2018-12-06 15:42 UTC, thermokarst commented on library/plugins/forms.py
> +                                        'Save the plugin to ad additional authors.', code='author_error1')
Typo: `s/ad/add/g`

2018-12-06 16:22 UTC, thermokarst commented
Oops, looks like you deleted a few files in that [most recent commit](https://github.com/qiime2/library/pull/22/commits/b2da962210b18ee905216fbcb4cbe2164e81f54a), @raptorace27.

2018-12-06 16:23 UTC, raptorace27 commented
Sweet! You just wanted us to change ‘ad’ to ‘add’ right?

2018-12-06 16:24 UTC, thermokarst commented
Yep, just fix the typo, no need to delete any files (as the PR stands now the code won't run because of those now-missing files).

2018-12-06 17:02 UTC, raptorace27 commented
Alrighty @thermokarst hopefully that did the job!

2018-12-08 17:42 UTC, thermokarst approved these changes

2018-12-08 17:44 UTC, merged

2018-12-08 17:47 UTC, thermokarst commented
Yeehaw! Lookin' good! Thanks team, this is awesome! These changes are now live at https://library.qiime2.org !!!

🎉 🎂

2018-12-08 17:51 UTC, raptorace27 commented
Whooo!!!! First PR to be merged! Thanks for all your help @thermokarst we can’t wait to keep working with you guys in the future!