MAINT: Updated copyright to current year in base.html
qiime2/library-old pull request #30
Opened 2019-06-25 23:39 UTC by Davrod29

Updated the copyright year in base.html

2019-06-27 17:41 UTC, Davrod29 commented
Just ran the command to delete any potentially .DS_Store file. The git status command didn't return any deleted files.

2019-06-27 18:16 UTC, ebolyen commented
@Davrod29, the diff still appears to have them

2019-06-28 15:26 UTC, thermokarst requested changes
Looks good @Davrod29, one minor thought (inline), which is a part of the task that we _didn't_ get a chance to talk about in the PPEF briefing (it totally slipped my mind - sorry!).

2019-06-28 15:26 UTC, thermokarst commented on library/templates/base.html
> +        &#169; 2019, <strong>QIIME 2 development team</strong>
Since this project was started in 2018, how about we keep that info in the updated copyright? So, something like:

```
2018-2019
```

2019-06-28 16:16 UTC, thermokarst approved these changes

2019-06-28 16:16 UTC, thermokarst commented
Thanks @Davrod29, looks great!

2019-06-28 16:17 UTC, merged